### PR TITLE
Landing PR test

### PR DESCRIPTION
**Pull request by CarsonWebster**
Here is what a github pull request looks like. 
Pull requests have a name, a longer description, and space for collaborators to comment / review with feedback!

The commit diffs and files updates / touched should also be displayed. 

To approve a PR and merge into main, 1 person reviewing is required. 

Once a single reviewer approves the changes, the branch can be merged into main and optionally deleted. A merged branch will have the merged tag / label until deleted or additional commits are pushed to that branch. 

Once a PR is published, you can still make edits to it! By checking out the branch, anyone is able to make commits and push to the branch. The existing PR will then be updated to reflect new commits.

### CODE REVIEW

**Comment by JamesFyfe** [comment]
Added functionality to pantry table.

**Review by troyschultz-ucsc — COMMENTED** [review]
Looks fine just added tables

**Review by troyschultz-ucsc — APPROVED** [review]
looks fine

**Review by troyschultz-ucsc — APPROVED** [review]
Looks fine

**Pull request merged**
